<?php

/**
 * UsersCommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsersCommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsersCommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsersComments');
    }
	public function  findAll($hydrationMode = null){  
        $q = Doctrine_Query::create()  
            ->select('c.*,u.name')  
            ->from('UsersComments c')  
            ->innerJoin('c.Users u');  
        return $q->execute();  
    }  
}