<?php

/**
 * Users
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Users extends BaseUsers
{
	public function addComment($text){  
        $comment = new UsersComments();  
        $comment->id_user = $this->id;  
        $comment->text = $text;  
        $comment->save();  
    }  
    public function  getName(){  
        if(empty($this->name) || is_null($this->name)){  
            return  "Desconocido";  
        }else{  
            return $this->name;  
        }  
    }  
}